# Generated by Django 4.0.4 on 2022-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_active_order_billing_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('shipped', 'Shipped'), ('refunded', 'Redunded'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
