# Generated by Django 4.0.4 on 2022-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('refunded', 'Redunded'), ('shipped', 'Shipped'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
