# Generated by Django 4.0.4 on 2023-02-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0114_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('refunded', 'Redunded'), ('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
