# Generated by Django 4.0.4 on 2023-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0118_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('refunded', 'Redunded'), ('paid', 'Paid'), ('created', 'Created'), ('shipped', 'Shipped')], default='created', max_length=120),
        ),
    ]
