# Generated by Django 4.0.4 on 2022-04-17 04:21

import amazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='amazon/sample.png', null=True, upload_to=amazon.models.upload_image_path),
        ),
    ]
