# Generated by Django 4.0.4 on 2022-04-18 02:45

import amazon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default='amazon/sample.png', null=True, upload_to=amazon.models.upload_image_path),
        ),
    ]
