# Generated by Django 4.0.4 on 2022-04-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
