version: '2'

services:
  db:
      image: postgres:latest
      ports:
        - "5554:5432"
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: amazon
      restart: always
      volumes:
        - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./webapp
      command: bash -c "./wait-for-it.sh db:5432 --strict -- ./initserver.sh"
      volumes:
        - ./webapp:/code
      depends_on:
        - db
  web:
      restart: always
      build: ./webapp
      user: nobody
#      command: bash -c "chmod +x ./runserver.sh; ./runserver.sh"
      command: /code/runserver.sh
      volumes:
        - ./webapp:/code
      ports:
        - "8000:8000"
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "80:80"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d
     depends_on:
       - web
  # daemon should run after the front-end has setted up(since we need the data from it, e.g. warehouse)
  amazonbackend:
    build: ./amazonBackend
    command: bash -c "./gradlew run"
    ports:
#      - "9999:9999" # port for UPS
      - "8888:8888" # port for web
    depends_on:
      - web
volumes:
   data-volume: 
